name: Deploy StockWeather Backend to Cloud Run

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 이 워크플로우 실행

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast3 # Artifact Registry와 Cloud Run의 리전을 일치시킵니다.
  SERVICE_NAME: stockweather-backend # Cloud Run 서비스 이름
  ARTIFACT_REGISTRY_REPO: cloud-run-source-deploy # ⭐ Artifact Registry 저장소 이름 (Cloud Build 기본값 또는 사용자 지정 필요)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud auth
        # ⭐ Artifact Registry 도메인으로 Docker 인증 구성
        run: gcloud auth configure-docker --repository=${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Debug GCloud Authentication Status
        run: gcloud auth list

      - name: Build and Deploy to Cloud Run
        run: |
          # Artifact Registry 경로를 사용하여 이미지 빌드 및 태그 지정
          IMAGE_NAME=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.SERVICE_NAME }}:latest
          
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE_NAME \ # ⭐ Artifact Registry 경로를 사용하여 이미지 참조
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars \
              DB_HOST=${{ secrets.DB_HOST }}, \
              DB_PORT=${{ secrets.DB_PORT }}, \
              DB_USERNAME=${{ secrets.DB_USERNAME }}, \
              DB_DATABASE=${{ secrets.DB_DATABASE }}, \
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}, \
              DB_SSL_ENABLED=${{ secrets.DB_SSL_ENABLED }}, \
              NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}, \
              NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}, \
              KOREA_INVEST_APP_KEY=${{ secrets.KOREA_INVEST_APP_KEY }}, \
              KOREA_INVEST_APP_SECRET=${{ secrets.KOREA_INVEST_APP_SECRET }}
        working-directory: .