# .github/workflows/deploy-functions.yml
name: Deploy REST API to Cloud Functions

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 워크플로우 실행

env:
  PROJECT_ID: stockweather
  REGION: asia-northeast3
  FUNCTION_NAME: stockweather-rest-api # Cloud Functions 함수 이름 (원하는 이름으로 변경)
  GCP_SERVICE_ACCOUNT: stockweather-db-connect@stockweather.iam.gserviceaccount.com # 서비스 계정 확인
  
  # Cloud Functions용 환경 변수 (NestJS ConfigService에서 사용될 값들)
  # Cloud Functions는 Docker 이미지를 사용하지 않고 소스 코드를 배포하므로,
  # 환경 변수들을 --set-env-vars 플래그를 통해 직접 전달해야 합니다.
  MODE: 'REST'
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  # 비밀 값은 secrets에서 가져옵니다.
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_SYNCHRONIZE: 'false' # 프로덕션에서는 false 권장
  DB_LOGGING: 'false'
  DB_SSL_ENABLED: 'true' # SSL 사용 여부
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
  DART_OPENAPI_KEY: ${{ secrets.DART_OPENAPI_KEY }}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
  KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
  KAKAO_CALLBACK_URL: ${{ secrets.KAKAO_CALLBACK_URL }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  CLOUD_SQL_CONNECTION_NAME: stockweather:asia-northeast3:stockweather # Cloud SQL 연결 이름

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Google Cloud 인증에 필요

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      # Google Cloud 인증 (Workload Identity Federation 사용)
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          # ⭐⭐ 워크로드 아이덴티티 풀 ID와 프로바이더 ID를 GCP 설정과 일치시킵니다. ⭐⭐
          # Pool ID: github-pool (확인됨)
          # Provider ID: <YOUR_ACTUAL_PROVIDER_ID> (GCP 콘솔에서 정확히 확인 필요)
          workload_identity_provider: 'projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/<YOUR_ACTUAL_PROVIDER_ID>'
          service_account: '${{ env.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Install dependencies'
        run: npm ci # 종속성 설치 (Cloud Functions가 빌드할 때 필요)

      - name: 'Build NestJS application'
        run: npm run build # NestJS 애플리케이션 빌드 (dist 폴더 생성)

      - name: 'Deploy to Cloud Functions'
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --entry-point=app \ # main.ts에서 export하는 Express 앱 인스턴스 이름
            --runtime=nodejs20 \ # Node.js 런타임 버전 (package.json의 engines 또는 선호 버전에 맞춤)
            --trigger-http \ # HTTP 요청으로 트리거
            --allow-unauthenticated \ # 외부에서 인증 없이 접근 허용 (JWT는 앱 내에서 처리)
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --service-account=${{ env.GCP_SERVICE_ACCOUNT }} \
            --memory=256MB \ # 함수 메모리 설정 (필요에 따라 조정)
            --timeout=300s \ # 함수 타임아웃 설정 (필요에 따라 조정)
            --add-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} \ # Cloud SQL 연결 설정
            --set-env-vars \
              MODE=${{ env.MODE }}, \
              DB_HOST=${{ env.DB_HOST }}, \
              DB_PORT=${{ env.DB_PORT }}, \
              DB_USERNAME=${{ env.DB_USERNAME }}, \
              DB_PASSWORD=${{ env.DB_PASSWORD }}, \
              DB_DATABASE=${{ env.DB_DATABASE }}, \
              DB_SYNCHRONIZE=${{ env.DB_SYNCHRONIZE }}, \
              DB_LOGGING=${{ env.DB_LOGGING }}, \
              DB_SSL_ENABLED=${{ env.DB_SSL_ENABLED }}, \
              JWT_SECRET=${{ env.JWT_SECRET }}, \
              CHATGPT_API_KEY=${{ env.CHATGPT_API_KEY }}, \
              DART_OPENAPI_KEY=${{ env.DART_OPENAPI_KEY }}, \
              KAKAO_CLIENT_ID=${{ env.KAKAO_CLIENT_ID }}, \
              KAKAO_CLIENT_SECRET=${{ env.KAKAO_CLIENT_SECRET }}, \
              KAKAO_CALLBACK_URL=${{ env.KAKAO_CALLBACK_URL }}, \
              FRONTEND_URL=${{ env.FRONTEND_URL }}, \
              CLOUD_SQL_CONNECTION_NAME=${{ env.CLOUD_SQL_CONNECTION_NAME }}
            # --source=. \ # 현재 디렉토리를 소스로 사용. .gcloudignore 파일 중요.
            # --entry-point는 package.json의 main 필드를 따르지 않으므로 직접 명시해야 합니다.
            # `package.json`의 `main` 필드를 `dist/main.js`로 지정하고,
            # `nest build`가 `dist` 폴더에 빌드된 파일을 생성한다면,
            # Cloud Functions는 `dist` 폴더를 기반으로 `app` 함수를 찾습니다.
            # `.gcloudignore` 파일을 통해 `events` 모듈이나 `node_modules` 중 필요 없는 것을 제외할 수 있습니다.