# .github/workflows/deploy.yml (수정 제안)
name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 워크플로우 실행
    # paths: # ⭐️ 이 부분을 주석 처리하거나 제거해야 합니다.
    #   - 'backend/**' 
      # 저장소 루트가 이미 백엔드 폴더이므로, 모든 변경사항에 대해 트리거해야 합니다.
      # 특정 파일/폴더를 지정하고 싶다면, 'src/**', 'Dockerfile' 등으로 변경해야 합니다.
      # 여기서는 모든 푸시에 대해 워크플로우가 실행되도록 paths를 제거합니다.

env:
  GCP_PROJECT_ID: stockweather 
  GCP_REGION: asia-northeast3 
  ARTIFACT_REGISTRY_REPO: cloud-run-source-deploy 
  SERVICE_NAME: stockweather-backend 
  GCP_SQL_INSTANCE_CONNECTION_NAME: stockweather:asia-northeast3:stockweather-cloud-sql 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ env.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'stockweather-db-connect@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Docker Login to Artifact Registry
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Build and Deploy to Cloud Run
      run: |
        IMAGE_NAME=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.SERVICE_NAME }}:latest
        
        # Dockerfile이 저장소 루트에 있으므로 빌드 컨텍스트는 '.'이 맞습니다.
        # working-directory가 './backend'가 아니므로, Dockerfile 경로를 명시해야 할 수 있습니다.
        # 하지만 스크린샷에서 Dockerfile이 루트에 있는 것으로 보이므로 이대로 괜찮을 수 있습니다.
        # Dockerfile이 'stockweather-backend' 루트에 있다면 아래 코드는 괜찮습니다.
        docker build -t $IMAGE_NAME . 
        docker push $IMAGE_NAME

        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $IMAGE_NAME \
          --platform managed \
          --region ${{ env.GCP_REGION }} \
          --allow-unauthenticated \
          --add-cloudsql-instances ${{ env.GCP_SQL_INSTANCE_CONNECTION_NAME }} \
          --set-env-vars DB_HOST=127.0.0.1 \
          --set-env-vars DB_PORT=5432 \
          --set-env-vars DB_USERNAME=${{ secrets.DB_USERNAME }} \
          --set-env-vars DB_DATABASE=${{ secrets.DB_DATABASE }} \
          --set-env-vars DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --set-env-vars DB_SSL_ENABLED=false \
          --set-env-vars KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
          --set-env-vars KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
          --set-env-vars KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }} \
          --set-env-vars JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --set-env-vars CHATGPT_API_KEY=${{ secrets.CHATGPT_API_KEY }} \
          --set-env-vars FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
          --set-env-vars DB_SYNCHRONIZE=false \
          --set-env-vars DB_LOGGING=false \
          --set-env-vars DART_OPENAPI_KEY=${{ secrets.DART_OPENAPI_KEY }} \
          --timeout=600s \
          --port 8080 
      # working-directory: ./backend # ⭐️ 이 라인을 제거해야 합니다! 저장소 루트가 백엔드입니다.