name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: stockweather # 본인의 Google Cloud 프로젝트 ID로 변경
  SERVICE_NAME: stockweather-backend # Cloud Run 서비스 이름
  REGION: asia-northeast3 # Cloud Run 배포 리전
  GCP_ARTIFACT_REGISTRY: asia-northeast3-docker.pkg.dev/stockweather/stockweather-backend # Artifact Registry 리포지토리 경로
  GCP_SERVICE_ACCOUNT: stockweather-db-connect@stockweather.iam.gserviceaccount.com # 서비스 계정 이메일
  GCP_SQL_INSTANCE_CONNECTION_NAME: stockweather:asia-northeast3:stockweather-db # Cloud SQL 인스턴스 연결 이름
  DB_HOST: 127.0.0.1 # Cloud SQL Proxy 사용 시
  DB_PORT: 5432 # PostgreSQL 기본 포트
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_SYNCHRONIZE: ${{ secrets.DB_SYNCHRONIZE }}
  DB_LOGGING: ${{ secrets.DB_LOGGING }}
  DB_SSL_ENABLED: ${{ secrets.DB_SSL_ENABLED }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
  DART_OPENAPI_KEY: ${{ secrets.DART_OPENAPI_KEY }}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
  KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
  KAKAO_CALLBACK_URL: ${{ secrets.KAKAO_CALLBACK_URL }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Workload Identity Federation 사용 시 필요하지만, 여기서는 credentials_json을 사용하므로 크게 상관없음

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      # Google Cloud 인증 (서비스 계정 키 사용)
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # GitHub Secrets에 저장된 서비스 계정 키 사용

      # Artifact Registry에 Docker 로그인
      - name: 'Set up Cloud SDK and Docker auth'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          # gcloud auth configure-docker artifact-registry는 credentials_json으로 인증된 상태에서 자동 처리됨

      - name: 'Configure Docker to use the gcloud command'
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Docker 이미지 빌드
      - name: 'Build Docker image'
        run: |
          docker build -t ${{ env.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }} . # 현재 커밋 SHA를 태그로 사용

      # Docker 이미지 Artifact Registry에 푸시
      - name: 'Push Docker image to Artifact Registry'
        run: |
          docker push ${{ env.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }}

      # Cloud Run에 배포
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GCP_ARTIFACT_REGISTRY }}:${{ github.sha }}
          # --service-account 플래그 제거 (credentials_json으로 인증하므로 필요 없음)
          flags: |
            --allow-unauthenticated
            --set-env-vars DB_HOST=${{ env.DB_HOST }}
            --set-env-vars DB_PORT=${{ env.DB_PORT }}
            --set-env-vars DB_USERNAME=${{ env.DB_USERNAME }}
            --set-env-vars DB_PASSWORD=${{ env.DB_PASSWORD }}
            --set-env-vars DB_DATABASE=${{ env.DB_DATABASE }}
            --set-env-vars DB_SYNCHRONIZE=${{ env.DB_SYNCHRONIZE }}
            --set-env-vars DB_LOGGING=${{ env.DB_LOGGING }}
            --set-env-vars DB_SSL_ENABLED=${{ env.DB_SSL_ENABLED }}
            --set-env-vars JWT_SECRET=${{ env.JWT_SECRET }}
            --set-env-vars CHATGPT_API_KEY=${{ env.CHATGPT_API_KEY }}
            --set-env-vars DART_OPENAPI_KEY=${{ env.DART_OPENAPI_KEY }}
            --set-env-vars KAKAO_CLIENT_ID=${{ env.KAKAO_CLIENT_ID }}
            --set-env-vars KAKAO_CLIENT_SECRET=${{ env.KAKAO_CLIENT_SECRET }}
            --set-env-vars KAKAO_CALLBACK_URL=${{ env.KAKAO_CALLBACK_URL }}
            --set-env-vars FRONTEND_URL=${{ env.FRONTEND_URL }}
            --add-cloudsql-instances ${{ env.GCP_SQL_INSTANCE_CONNECTION_NAME }}
            --timeout 300 # 타임아웃 300초 (5분) 설정