# .github/workflows/deploy-websocket.yml
name: Deploy WebSocket to Cloud Run

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 워크플로우 실행

# env 섹션은 이제 사용하지 않거나 최소화합니다.
# 모든 구성은 secrets에서 가져옵니다.

jobs:
  deploy-websocket:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # GitHub Secret
          service_account: '${{ secrets.GCP_SA_EMAIL }}' # GitHub Secret

      - name: 'Set up Cloud SDK and Docker auth'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }} # GitHub Secret

      - name: 'Configure Docker to use the gcloud command'
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev # GitHub Secret

      - name: 'Build Docker image for WebSocket'
        run: docker build -t ${{ secrets.GCP_AR_IMAGE_PATH_WEBSOCKET }}:${{ github.sha }} . # GitHub Secret

      - name: 'Push Docker image to Artifact Registry'
        run: docker push ${{ secrets.GCP_AR_IMAGE_PATH_WEBSOCKET }}:${{ github.sha }} # GitHub Secret

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ secrets.GCP_CR_NAME_WEBSOCKET }} # GitHub Secret
          region: ${{ secrets.GCP_REGION }} # GitHub Secret
          image: ${{ secrets.GCP_AR_IMAGE_PATH_WEBSOCKET }}:${{ github.sha }} # GitHub Secret
          flags: |
            --allow-unauthenticated
            --timeout 300
            --service-account ${{ secrets.GCP_SA_EMAIL }} # GitHub Secret
            --add-cloudsql-instances ${{ secrets.GCP_SQL_CONNECTION_NAME }} # GitHub Secret
            # 민감하지 않은 앱 환경 변수는 --set-env-vars로 직접 설정
            --set-env-vars="MODE=WS,DB_HOST=127.0.0.1,DB_PORT=5432,DB_SYNCHRONIZE=false,DB_LOGGING=false,DB_SSL_ENABLED=true,CLOUD_SQL_CONNECTION_NAME=${{ secrets.GCP_SQL_CONNECTION_NAME }}"
            # 민감한 앱 환경 변수는 --set-secrets로 Secret Manager에서 가져옴
            --set-secrets="DB_USERNAME=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/DB_USERNAME:latest,\
              DB_PASSWORD=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/DB_PASSWORD:latest,\
              DB_DATABASE=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/DB_DATABASE:latest,\
              JWT_SECRET=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/JWT_SECRET:latest,\
              FRONTEND_URL=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/FRONTEND_URL:latest"
            --port 3000
            --min-instances 1
          env_vars_update_strategy: merge
          secrets_update_strategy: merge