name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 워크플로우 실행
    # paths: # ⭐️ 이 부분을 제거했습니다. 저장소 루트가 백엔드이므로, 백엔드 코드 변경에 항상 트리거됩니다.
    #   - 'backend/**' 

env:
  GCP_PROJECT_ID: stockweather 
  GCP_REGION: asia-northeast3 
  ARTIFACT_REGISTRY_REPO: cloud-run-source-deploy 
  SERVICE_NAME: stockweather-backend 
  # ⭐ Cloud SQL 인스턴스 연결 이름이 정확한지 다시 한번 확인하세요! ⭐
  GCP_SQL_INSTANCE_CONNECTION_NAME: stockweather:asia-northeast3:stockweather-cloud-sql 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Google Cloud 인증에 필요

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ env.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        # ⭐⭐ 서비스 계정 이메일 주소가 IAM에서 확인한 것과 정확히 일치하는지 다시 한번 확인하세요! ⭐⭐
        service_account: 'stockweather-db-connect@stockweather.iam.gserviceaccount.com'

    - name: Docker Login to Artifact Registry
      # Docker 빌드 및 푸시를 위해 Artifact Registry에 로그인합니다.
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Build and Deploy to Cloud Run
      run: |
        IMAGE_NAME=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.SERVICE_NAME }}:latest
        
        # Dockerfile이 저장소 루트에 있으므로, 현재 디렉토리(.)를 빌드 컨텍스트로 사용합니다.
        docker build -t $IMAGE_NAME . 
        docker push $IMAGE_NAME

        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $IMAGE_NAME \
          --platform managed \
          --region ${{ env.GCP_REGION }} \
          --allow-unauthenticated \
          --add-cloudsql-instances ${{ env.GCP_SQL_INSTANCE_CONNECTION_NAME }} \
          # ⭐ 모든 Secrets 값이 GitHub 저장소 설정에 정확히 등록되어 있는지 확인! ⭐
          --set-env-vars DB_HOST=127.0.0.1 \
          --set-env-vars DB_PORT=5432 \
          --set-env-vars DB_USERNAME=${{ secrets.DB_USERNAME }} \
          --set-env-vars DB_DATABASE=${{ secrets.DB_DATABASE }} \
          --set-env-vars DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --set-env-vars DB_SSL_ENABLED=false \
          --set-env-vars KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
          --set-env-vars KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
          --set-env-vars KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }} \
          --set-env-vars JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --set-env-vars CHATGPT_API_KEY=${{ secrets.CHATGPT_API_KEY }} \
          --set-env-vars FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
          --set-env-vars DB_SYNCHRONIZE=false \
          --set-env-vars DB_LOGGING=false \
          --set-env-vars DART_OPENAPI_KEY=${{ secrets.DART_OPENAPI_KEY }} \
          --timeout=600s \
          --port 8080 
      # working-directory: ./backend # ⭐️ 이 라인을 제거했습니다. 저장소 루트가 백엔드이므로 불필요합니다.