# 🚀 Deploy Backend (WebSocket + REST API)

name: Deploy Backend (WebSocket + REST API)

on:
  push:
    branches:
      - main

jobs:
  deploy-websocket:
    name: Deploy WebSocket (Cloud Run)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Configure Docker to use gcloud'
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: 'Build Docker image for WebSocket'
        run: docker build --build-arg ENTRY_FILE=bootstrap-ws -t ${{ secrets.GCP_AR_IMAGE_PATH_WEBSOCKET }}:${{ github.sha }} .

      - name: 'Push Docker image to Artifact Registry'
        run: docker push ${{ secrets.GCP_AR_IMAGE_PATH_WEBSOCKET }}:${{ github.sha }}

      - name: 'Remove old env var (WebSocket)'
        run: |
          gcloud run services update ${{ secrets.GCP_CR_NAME_WEBSOCKET }} \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --remove-env-vars=FRONTEND_URL || true

      - name: 'Deploy WebSocket to Cloud Run'
        run: |
          gcloud run deploy ${{ secrets.GCP_CR_NAME_WEBSOCKET }} \
            --image=${{ secrets.GCP_AR_IMAGE_PATH_WEBSOCKET }}:${{ github.sha }} \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --timeout=300 \
            --service-account=${{ secrets.GCP_SA_EMAIL }} \
            --add-cloudsql-instances=${{ secrets.GCP_SQL_CONNECTION_NAME }} \
            --memory=512Mi \
            --ingress=all \
            --set-env-vars="\
              NODE_ENV=production,\
              MODE=WS,\
              DB_HOST=/cloudsql/${{ secrets.GCP_SQL_CONNECTION_NAME }},\
              DB_PORT=5432,\
              DB_SYNCHRONIZE=false,\
              DB_LOGGING=false,\
              DB_SSL_ENABLED=false,\
              CLOUD_SQL_CONNECTION_NAME=${{ secrets.GCP_SQL_CONNECTION_NAME }},\
              FRONTEND_URL=https://stockweather-frontend.vercel.app" \
            --update-secrets="\
              DB_USERNAME=DB_USERNAME:latest,\
              DB_PASSWORD=DB_PASSWORD:latest,\
              DB_DATABASE=DB_DATABASE:latest,\
              JWT_SECRET=JWT_SECRET:latest,\
              CHATGPT_API_KEY=CHATGPT_API_KEY:latest,\
              DART_OPENAPI_KEY=DART_OPENAPI_KEY:latest,\
              KAKAO_CLIENT_ID=KAKAO_CLIENT_ID:latest,\
              KAKAO_CLIENT_SECRET=KAKAO_CLIENT_SECRET:latest,\
              KAKAO_CALLBACK_URL=KAKAO_CALLBACK_URL:latest" \
            --port=8080 \
            --min-instances=1 \
            --use-http2 \
            --quiet

      - name: 'Move traffic to latest revision (WebSocket)'
        run: |
          gcloud run services update-traffic ${{ secrets.GCP_CR_NAME_WEBSOCKET }} \
            --to-latest \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed

      - name: 'Clean up old revisions (WebSocket)'
        run: |
          OLD_REVISIONS=$(gcloud run revisions list --service=${{ secrets.GCP_CR_NAME_WEBSOCKET }} --region=${{ secrets.GCP_REGION }} --platform=managed --filter="traffic:0" --format="value(METADATA.name)")
          for REV in $OLD_REVISIONS; do
            echo "Deleting old revision: $REV"
            gcloud run revisions delete $REV --region=${{ secrets.GCP_REGION }} --platform=managed --quiet
          done

  deploy-rest-api:
    name: Deploy REST API (Cloud Run)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    needs: deploy-websocket

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: 'Configure Docker to use gcloud'
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: 'Build Docker image for REST API'
        run: docker build --build-arg ENTRY_FILE=bootstrap-rest -t ${{ secrets.GCP_AR_IMAGE_PATH_REST_API }}:${{ github.sha }} .

      - name: 'Push Docker image to Artifact Registry'
        run: docker push ${{ secrets.GCP_AR_IMAGE_PATH_REST_API }}:${{ github.sha }}

      - name: 'Remove old env var (REST API)'
        run: |
          gcloud run services update ${{ secrets.GCP_CR_NAME_REST_API }} \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --remove-env-vars=FRONTEND_URL || true

      - name: 'Deploy REST API to Cloud Run'
        run: |
          gcloud run deploy ${{ secrets.GCP_CR_NAME_REST_API }} \
            --image=${{ secrets.GCP_AR_IMAGE_PATH_REST_API }}:${{ github.sha }} \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --timeout=300 \
            --service-account=${{ secrets.GCP_SA_EMAIL }} \
            --add-cloudsql-instances=${{ secrets.GCP_SQL_CONNECTION_NAME }} \
            --memory=512Mi \
            --ingress=all \
            --set-env-vars="\
              NODE_ENV=production,\
              MODE=REST,\
              DB_HOST=/cloudsql/${{ secrets.GCP_SQL_CONNECTION_NAME }},\
              DB_PORT=5432,\
              DB_SYNCHRONIZE=false,\
              DB_LOGGING=false,\
              DB_SSL_ENABLED=false,\
              CLOUD_SQL_CONNECTION_NAME=${{ secrets.GCP_SQL_CONNECTION_NAME }},\
              FRONTEND_URL=https://stockweather-frontend.vercel.app" \
            --update-secrets="\
              DB_USERNAME=DB_USERNAME:latest,\
              DB_PASSWORD=DB_PASSWORD:latest,\
              DB_DATABASE=DB_DATABASE:latest,\
              JWT_SECRET=JWT_SECRET:latest,\
              CHATGPT_API_KEY=CHATGPT_API_KEY:latest,\
              DART_OPENAPI_KEY=DART_OPENAPI_KEY:latest,\
              KAKAO_CLIENT_ID=KAKAO_CLIENT_ID:latest,\
              KAKAO_CLIENT_SECRET=KAKAO_CLIENT_SECRET:latest,\
              KAKAO_CALLBACK_URL=KAKAO_CALLBACK_URL:latest" \
            --port=8080 \
            --min-instances=0 \
            --use-http2 \
            --quiet

      - name: 'Move traffic to latest revision (REST API)'
        run: |
          gcloud run services update-traffic ${{ secrets.GCP_CR_NAME_REST_API }} \
            --to-latest \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed

      - name: 'Clean up old revisions (REST API)'
        run: |
          OLD_REVISIONS=$(gcloud run revisions list --service=${{ secrets.GCP_CR_NAME_REST_API }} --region=${{ secrets.GCP_REGION }} --platform=managed --filter="traffic:0" --format="value(METADATA.name)")
          for REV in $OLD_REVISIONS; do
            echo "Deleting old revision: $REV"
            gcloud run revisions delete $REV --region=${{ secrets.GCP_REGION }} --platform=managed --quiet
          done
