# .github/workflows/deploy-functions.yml
name: Deploy REST API to Cloud Functions

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 워크플로우 실행

env:
  PROJECT_ID: stockweather
  REGION: asia-northeast3
  FUNCTION_NAME: stockweather-rest-api # Cloud Functions 함수 이름 (원하는 이름으로 변경)
  GCP_SERVICE_ACCOUNT: stockweather-db-connect@stockweather.iam.gserviceaccount.com # 서비스 계정 확인

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          service_account: '${{ env.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build NestJS application'
        run: npm run build

      - name: 'Deploy to Cloud Functions'
        # ⭐⭐⭐ 모든 플래그를 한 줄로 붙여서 전달합니다. ⭐⭐⭐
        run: gcloud functions deploy ${{ env.FUNCTION_NAME }} --entry-point=app --runtime=nodejs20 --trigger-http --allow-unauthenticated --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }} --service-account=${{ env.GCP_SERVICE_ACCOUNT }} --memory=256MB --timeout=300s --add-cloudsql-instances=${{ env.CLOUD_SQL_CONNECTION_NAME }} --set-env-vars="MODE=REST,DB_HOST=127.0.0.1,DB_PORT=5432,DB_SYNCHRONIZE=false,DB_LOGGING=false,DB_SSL_ENABLED=true,CLOUD_SQL_CONNECTION_NAME=stockweather:asia-northeast3:stockweather" --set-secrets="DB_USERNAME=projects/${{ env.PROJECT_ID }}/secrets/DB_USERNAME:latest,DB_PASSWORD=projects/${{ env.PROJECT_ID }}/secrets/DB_PASSWORD:latest,DB_DATABASE=projects/${{ env.PROJECT_ID }}/secrets/DB_DATABASE:latest,JWT_SECRET=projects/${{ env.PROJECT_ID }}/secrets/JWT_SECRET:latest,CHATGPT_API_KEY=projects/${{ env.PROJECT_ID }}/secrets/CHATGPT_API_KEY:latest,DART_OPENAPI_KEY=projects/${{ env.PROJECT_ID }}/secrets/DART_OPENAPI_KEY:latest,KAKAO_CLIENT_ID=projects/${{ env.PROJECT_ID }}/secrets/KAKAO_CLIENT_ID:latest,KAKAO_CLIENT_SECRET=projects/${{ env.PROJECT_ID }}/secrets/KAKAO_CLIENT_SECRET:latest,KAKAO_CALLBACK_URL=projects/${{ env.PROJECT_ID }}/secrets/KAKAO_CALLBACK_URL:latest,FRONTEND_URL=projects/${{ env.PROJECT_ID }}/secrets/FRONTEND_URL:latest"